
services:
  db:
    image: postgres:16
    container_name: db_delivery
    ports:
      - "5432:5432"
    volumes:
      - ../data:/var/lib/postgresql/data
#      - ../users_dlv.csv:/users_dlv.csv
      - ../users_dlv.csv:/var/lib/pgadmin/storage/delivery_admin.com/users_dlv.csv
    env_file:
      - .env


  pgadmin:
    image: elestio/pgadmin
    container_name: pgdelivery_admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ../users_dlv.csv:/users_dlv.csv
    env_file:
      - .env


  bot:
    build:
      context: ..
      dockerfile: docker/dockerfiles/DockerfileBot
      args:
        - --no-cache
    container_name: bot_delivery
    volumes:
      - ../bot:/app
      - ../logs/bot:/app/logs/
    depends_on:
      - db
    env_file:
      - .env

  web:
    build:
      context: ..
      dockerfile: docker/dockerfiles/DockerfileAdmin
      args:
        - --no-cache
    container_name: web_delivery
    volumes:
      - ../delivery_admin:/app
      - ../logs/django:/app/logs/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env


  nginx:
    image: nginx:latest
    container_name: nginx_delivery
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d/base.conf:/etc/nginx/conf.d/base.conf
      - ../delivery_admin/static:/var/html/static/
      - ../delivery_admin/staticfiles:/var/html/staticfiles/
      - ../delivery_admin/media:/var/html/media/
      - ../logs/nginx:/var/log/nginx
    depends_on:
      - web


volumes:
  pgadmin_data:


